/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CIRCULO_H_RPCGEN
#define _CIRCULO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define CIRCULO_PROG 0x31111111
#define CIRCULO_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CIRCUNFERENCIA 1
extern  double * circunferencia_1(radio *, CLIENT *);
extern  double * circunferencia_1_svc(radio *, struct svc_req *);
#define AREA 2
extern  double * area_1(radio *, CLIENT *);
extern  double * area_1_svc(radio *, struct svc_req *);
extern int circulo_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CIRCUNFERENCIA 1
extern  double * circunferencia_1();
extern  double * circunferencia_1_svc();
#define AREA 2
extern  double * area_1();
extern  double * area_1_svc();
extern int circulo_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CIRCULO_H_RPCGEN */
